### ISSUE TITLE
Redish Purple Liquid Not Functioning Properly

### ISSUE THREAD

**Issue by mitchell11678** [JayAvery/jjmod#1]
I'm not sure what this liquid is supposed to be, however, when you jump into it you do not swim, you just fall through it as if it weren't there. It does still flow like a liquid however.
![2017-07-04_21 32 30](https://user-images.githubusercontent.com/2841186/27846968-52e77e70-6100-11e7-9676-8bd72d384404.png)
![2017-07-04_21 32 56](https://user-images.githubusercontent.com/2841186/27846977-5d575682-6100-11e7-9ca0-418665079484.png)

**Comment by averixus** [comment]
Thanks for the report. This liquid is tar and it's still somewhat a work in progress (it doesn't currently.. DO anything), but it should be getting improved at some point.

**Comment by averixus** [comment]
Fixed in 2.0.0!
