### ISSUE TITLE
Inventory doesn't synchronise properly in some situations

### ISSUE THREAD

**Issue by averixus** [JayAvery/jjmod#12]
- Using /give command
- Using JEI recipe fill
- Sometimes when picking up items? ( #9  )

In all cases, the GUI doesn't show the updated inventory, but when the relevant slot is clicked the correct stack appears - items are never actually lost, just invisible.

I'm having trouble finding the cause - help would be appreciated! If you have more examples of when this issue occurs, please add them here.

**Comment by SigurdCole** [comment]
Here's an odd one:

Have a nearly broken flint axe.
Make a new axe.
Axe breaks, slot new axe into old axe's empty slot.
New axe is placed, old axe is put in my hand.
Proceed to cut down a whole tree with a zero durability flint axe.

**Comment by averixus** [comment]
This issue is provisionally fixed in 1.1.1. But to be honest I don't _entirely_ understand what the problem was - so it might not be totally eliminated, or might return in unexpected ways. Please comment again if you notice any syncing issues and I will reopen.
