### ISSUE TITLE
Pole roof not staying up

### ISSUE THREAD

**Issue by SigurdCole** [JayAvery/jjmod#14]
I've been trying to build my first shelter, but the roof won't stay up!

[Image reference](https://imgur.com/uR2yqfM)

Basically, log wall - space - space - log wall. I've placed the roof on top of the wall, and have been extending it from there. Any pole roof not placed directly atop a wood wall will spontaneously pop off over time. I've been careful to not jump anywhere near them or anything, but it keeps happening.

**Comment by averixus** [comment]
I built the same setup as the screenshot and let it run for about half an hour - and none of the roof blocks broke. A mystery! I'm not quite sure where to go from here.

Do the roof blocks drop themselves as items, or disappear completely? Have you noticed any association with weather or other conditions? Have you tried building the same setup in a different location? Is it possible that other entities are walking on the blocks making them break?

**Comment by SigurdCole** [comment]
Nothing I can think of, other than the forge under it. Half of the time I've been well away from it when they've popped so it seems to just be a block update thing?

I've mostly murdered the nearby wildlife by now, so I'm confident it isn't a curious sheep's fault. 

They do drop the pole roof items when they go.

I haven't tried building it elsewhere yet, but I'll try raising the roof by a block to see if an air gap makes a difference.

**Comment by SigurdCole** [comment]
Just tested in creative without mods, had it happen again. [Picture here.](http://i.imgur.com/QIL6sTN.png)

Looks like giving the forge an air-gap didn't make a difference.

I tried loading and unloading the chunk, but that didn't seem to have an effect.

Would it help if I uploaded my save somewhere?

**Comment by SigurdCole** [comment]
Aaaand I spoke too soon. To test, I had started to add back in mods. It seems that either InControl (which I use to control mob spawning) or CompatLayer (its dependency) may be to blame. Or bats. It might be bats.

I know you're not interested in compatibility issues at this time. I'll see if McJty is willing to give it a look, if it's okay.

**Comment by SigurdCole** [comment]
....it's bats

**Comment by averixus** [comment]
As of 1.1.1, bats no longer destroy flat roofs!
