### ISSUE TITLE
Can walk between log wall blocks

### ISSUE THREAD

**Issue by SigurdCole** [JayAvery/jjmod#20]
Hi!

Just found this one. Doesn't seem dependent on how they're placed (on the ground or against each other). Cannot get it to consistently reproduce. Seems to happen when they're in close proximity to other log walls.

Thanks for all your hard work!

**Comment by averixus** [comment]
This should be fixed in 1.1.1 - comment again if you find it happens again. Pictures or video of particular situations would be good if it does happen again.
