### ISSUE TITLE
Couldn't run properly in Sponge 1.11.2

### ISSUE THREAD

**Issue by TRLWeiss** [JayAvery/jjmod#56]
Running in Sponge, there are problems as below:
When in a creative mode to gain any food in Geomastery, it will just gain a rot one 

If using inventory mode of Geomastery ,  getting any drop item in Geomastery will crash and unable to gain the drop item.

When cutting down trees which belongs to custom trees,the fps will be down and sometimes running out of memories.    

Hope there will be a perfect update which provides a great game experience online.

Thanks!

**Comment by averixus** [comment]
To my understanding, SpongeForge is essentially just a Forge mod which can itself run Sponge plugins, so I can't see why it would cause major problems with Geomastery. Are you certain that SpongeForge is installed correctly? Are you running any Sponge plugins or other Forge mods which could be causing incompatibility?

If the game crashes, it would also be really helpful to see the full crash report please. Hopefully we can figure this out!

**Comment by TRLWeiss** [comment]
[23:12:31] [Server thread/ERROR] [Sponge]: /************************************
********************************************************************************
*******************/
> /*****************************************************************************
**********************************************************/
/*                                                     Exception during phase body                                                     */
/***************************************************************************************************************************************/
/* Something happened trying to run the main body of a phase PlayerTickPhase
                                                       */
/* PhaseContext :
                                                       */
/*         - Name: Source
                                                       */
/*           Object: EntityPlayerMP['test1'/256, l='world', x=133.30, y=67.68, z=9.47]                                                */
/*         - Name: CapturedBlocks
                                                       */
/*           Object: CapturedBlocksSupplier{Captured=0}
                                                       */
/*         - Name: CapturedEntities
                                                       */
/*           Object: CapturedEntitiesSupplier{Captured=0}
                                                       */
/* Phases remaining :
                                                       */
/*   - Phase: PlayerTickPhase
                                                       */
/*     Context:
                                                       */
/*     - Name: Source
                                                       */
/*       Object: EntityPlayerMP['test1'/256, l='world', x=133.30, y=67.68, z=9.47]                                                    */
/*     - Name: CapturedBlocks
                                                       */
/*       Object: CapturedBlocksSupplier{Captured=0}
                                                       */
/*     - Name: CapturedEntities
                                                       */
/*       Object: CapturedEntitiesSupplier{Captured=0}
                                                       */
/* Stacktrace:
                                                       */
/* net.minecraft.util.ReportedException: Ticking player
                                                       */
/*     net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.ja
va:406)                                                */
/*     net.minecraft.network.NetHandlerPlayServer.lambda$onPlayerTick$0(NetHandl
erPlayServer.java:1950)                                */
/*     org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseT
racker.java:162)                                       */
/*     net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zha000(N
etHandlerPlayServer.java:1949)                         */
/*     net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlaySer
ver.java:164)                                          */
/*     net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_
73660_a(NetworkDispatcher.java:215)                    */
/*     net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287
)                                                      */
/*     net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
                                                       */
/*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:74
3)                                                     */
/*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServ
er.java:384)                                           */
/*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:62
4)                                                     */
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
                                                       */
/*     java.lang.Thread.run(Unknown Source)
                                                       */
/* java.lang.IndexOutOfBoundsException: Index: 36, Size: 23
                                                       */
/*     java.util.ArrayList.rangeCheck(Unknown Source)
                                                       */
/*     java.util.ArrayList.get(Unknown Source)
                                                       */
/*     net.minecraft.inventory.Container.func_75139_a(Container.java:114)
                                                       */
/*     org.spongepowered.common.event.SpongeCommonEventFactory.callPlayerChangeI
nventoryPickupEvent(SpongeCommonEventFactory.java:161) */
/*     net.minecraft.entity.item.EntityItem.handler$onPlayerItemPickup$zej000(En
tityItem.java:808)                                     */
/*     net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:392)
                                                       */
/*     net.minecraft.entity.player.EntityPlayer.redirect$onPlayerCollideEntity$z
ff000(EntityPlayer.java:3609)                          */
/*     net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:5
82)                                                    */
/*     net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:5
74)                                                    */
/*     net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java
:2088)                                                 */
/*     net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:
232)                                                   */
/*     net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.ja
va:329)                                                */
/*     net.minecraft.network.NetHandlerPlayServer.lambda$onPlayerTick$0(NetHandl
erPlayServer.java:1950)                                */
/*     org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseT
racker.java:162)                                       */
/*     net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zha000(N
etHandlerPlayServer.java:1949)                         */
/*     net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlaySer
ver.java:164)                                          */
/*     net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_
73660_a(NetworkDispatcher.java:215)                    */
/*     net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287
)                                                      */
/*     net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
                                                       */
/*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:74
3)                                                     */
/*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServ
er.java:384)                                           */
/*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:62
4)                                                     */
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
                                                       */
/*     java.lang.Thread.run(Unknown Source)
                                                       */
/*
                                                       */
/* Minecraft : 1.11.2
                                                       */
/* SpongeAPI : 6.1.0-SNAPSHOT-c4a7afd
                                                       */
/* SpongeForge : 1.11.2-2393-6.1.0-BETA-2606
                                                       */
/* Minecraft Forge : 13.20.1.2393
                                                       */


When I was running spongeforge with gaining any drop item it will appear until i leave the item. 
No crash but just problems in the game.

**Comment by tyler489** [comment]
Sponge does wierd things to forge classes. If you happen to use one. Of those classes wierd things happen

**Comment by tyler489** [comment]
Do you happen to be canceling item drops through forge?

**Comment by TRLWeiss** [comment]
cancel item drops？do you mean input the command /gamerule doTileDrops false ?
I never configure any options that on Forge. Just install forge and Sponge and put Geomastery into the mods document. Then the bug will appear. 
What does "Wierd Things"means ?

**Comment by tyler489** [comment]
That was directed at the mod dev

**Comment by TRLWeiss** [comment]
Ok now I understand what you mean. 
Do you happen to be canceling item drops through forge?
I don't.

**Comment by averixus** [comment]
Oh, yes that'll be it - Geomastery cancels and replaces item drops using Forge events. This is necessary because our inventory functions very differently to vanilla, so that won't change. I guess that means we're incompatible with SpongeForge - sorry to disappoint!

**Comment by TRLWeiss** [comment]
Actually,if I configure the options "Inventory" and set it false,then i can pick up drop item without any problem on Sponge. However,that may cause the trouble in food rotting. All animals will no longer produce drop item when they are killed.
Also,when harvest any crops on the field, I could just gain all  rot food although it just be harvested right away.
Are the reasons  of  these questions the same to the reason why sponge is incapable to Geomastery ?

**Comment by averixus** [comment]
It sounds like those are all things which Geomastery controls using Forge events, which seems to be what causes problems with Spigot. :(
