### ISSUE TITLE
suggestion for mod compatibility( animania mod)

### ISSUE THREAD

**Issue by MrSeven590** [JayAvery/jjmod#60]
it might save some time and energy.

[https://minecraft.curseforge.com/projects/animania](url)

and there is any possible backport to 1.10.2?

**Comment by averixus** [comment]
We're not planning to add animania (or other mob mods) compatibility, because we _do_ have plans to overhaul mobs in Geomastery in future. I'm afraid a 1.10.2 version is not in the works (although I certainly won't reject it if someone else does it).
