### ISSUE TITLE
Sawpit

### ISSUE THREAD

**Issue by bamoibam** [JayAvery/jjmod#61]
I Don't know how to build a sawpit !
It's says "Something is in the way of this structure! " 
![2018-06-15_19 30 59](https://user-images.githubusercontent.com/40296818/41468197-5c31f2a6-70d3-11e8-9a8e-86af167ec740.png)

**Comment by averixus** [comment]
The sawpit has to be built over a long hole - details are in the wiki [here](https://geomastery.miraheze.org/wiki/Crafting_devices#Sawpit).
